"""Add profile fields to users

Revision ID: 3a6889f901ac
Revises: deb75a3f245c
Create Date: 2026-07-13 01:12:26.398322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6889f901ac'
down_revision: Union[str, Sequence[str], None] = 'deb75a3f245c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('food_stock', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'food_stock')
    op.drop_column('users', 'age')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
